### User sign up endpoint
POST http://localhost:5000/v1/user/
Content-Type: application/json

{"name": "Sefat", "company":"Amazon",
"address":"6320skaha", "phone":"78651789",
"email":"sefat1@amazon.com",
"password":"sefatkhan"  }



### User sign in endpoint
POST http://localhost:5000/v1/user/login
Content-Type: application/json

{"email":"sefat1@amazon.com", "password":"sefatkhan" }




### Get a user profile endpoint
Get http://localhost:5000/v1/user/
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNlZmF0MUBhbWF6b24uY29tIiwiaWF0IjoxNjU3ODU5MjcxLCJleHAiOjE2NTc4NjAxNzF9.5j8WBytSLFW5hf0JGB8H5Jf6qqS6uzJVbb8xlnDFSKk

{"email":"sefat1@amazon.com", "password":"sefatkhan" }