

### User sign up endpoint
POST http://localhost:5000/v1/user/
Content-Type: application/json

{"name": "Sefat", "company":"Amazon",
"address":"6320skaha", "phone":"78651789",
"email":"sefat1@amazon.com",
"password":"sefatkhan"  }


### User sign in endpoint
POST http://localhost:5000/v1/user/login
Content-Type: application/json

{"email":"sefat1@amazon.com", "password":"sefatkhan" }



### Get a user profile endpoint, token is access token
Get http://localhost:5000/v1/user/
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNlZmF0MUBhbWF6b24uY29tIiwiaWF0IjoxNjU4MDUyNzUwLCJleHAiOjE2NjA2NDQ3NTB9.Yi6cqMFwX1_yYFdz1PXgVbljK9N3XAFARWvvOoF8iXo

{"email":"sefat1@amazon.com", "password":"sefatkhan" }



### Get new tokens, token is refreshed token
GET http://localhost:5000/v1/tokens/new-access-jwt
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNlZmF0MUBhbWF6b24uY29tIiwiaWF0IjoxNjU4MDUyNzUwLCJleHAiOjE2NjA2NDQ3NTB9.Yi6cqMFwX1_yYFdz1PXgVbljK9N3XAFARWvvOoF8iXo



### Request reset-password 
POST http://localhost:5000/v1/user/reset-password
Content-Type: application/json

{"email":"sefat1@amazon.com"}



### Update new Password 
PATCH http://localhost:5000/v1/user/reset-password
Content-Type: application/json

{"email":"sefat1@amazon.com",
"pin": "140411",
"newPassword": "password3"
}